###
# Get Github Issues
GET {{baseUrl}}/repos/{{repo}}/issues
Authorization: Bearer {{githubToken}}
Accept: application/vnd.github+json

###
# localhost health
GET {{baseUrl}}/health

###
# localhost get issue
GET {{baseUrl}}/api/v1/github/troyatomic/expressjs-typescript/issue/2

###
# localhost image in issue
GET {{baseUrl}}/api/v1/github/troyatomic/expressjs-typescript/issue/1/image

###
# localhost image in issue
POST {{baseUrl}}/api/v1/github/troyatomic/expressjs-typescript/issue/1/comment
Content-Type: application/json

{
 "body": "hi troy"   
}